Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Lint/MissingSuper:
  Exclude:
    - 'app/services/**/*'

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'bin/bundle'
    - 'config/**/*'
    - 'db/migrate/**/*'

Metrics/BlockLength:
  Exclude:
    - 'app/admin/doctors.rb'

Layout/HashAlignment:
  EnforcedColonStyle: table